export const data = [
  {
    title: "Dubai: A Global Hub for Real Estate Investment",
    blog: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia odio vitae vestibulum vestibulum. Cras vehicula ultricies mauris, nec malesuada urna interdum id. Fusce ac velit eu ante feugiat auctor. Nulla facilisi. Praesent in nisi malesuada, placerat justo at, lacinia magna. Curabitur sit amet nunc id purus tincidunt tincidunt. Aliquam erat volutpat. Proin at leo eget neque egestas consectetur. Vivamus vel odio at magna consequat fringilla. Sed volutpat lacinia est vel sodales.",
    upload_date: "02 July 2021",
    tags: ["Trending", "Popular", "News"],
  },
  {
    title: "Exploring Real Estate Gems in Dubai's Downtown",
    blog: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse potenti. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer a fermentum purus. Nam sit amet hendrerit eros. In sed interdum risus. Cras vitae risus consectetur, efficitur nisl sed, vehicula orci. Mauris consequat, felis ut cursus consequat, magna velit dignissim libero, in ultricies tortor purus ut purus. Sed euismod nunc vitae urna suscipit faucibus.",
    upload_date: "02 July 2021",
    tags: ["Recent", "Discount", "Popular"],
  },
  {
    title: "Luxury Living in Dubai: Investment Insights",
    blog: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tristique nisl in tincidunt fringilla. Vivamus eleifend malesuada neque, nec pulvinar sapien volutpat sit amet. Integer scelerisque nisi et neque cursus, sit amet venenatis tortor gravida. Nunc vehicula ex ut nunc iaculis aliquam. Etiam vitae eros nec justo egestas vehicula. Duis vehicula nunc ac eros varius, ut ornare arcu suscipit. Quisque vel elit id nisi facilisis dapibus.",
    upload_date: "02 July 2021",
    tags: ["Trending", "News", "Popular"],
  },
  {
    title: "Top 5 Real Estate Investment Destinations Globally",
    blog: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam erat volutpat. Proin volutpat tellus sed lacus hendrerit, sit amet lacinia purus sodales. Morbi in orci purus. Sed efficitur ex vel erat tincidunt, a faucibus est ultricies. Pellentesque eu sapien ornare, dapibus eros nec, dictum mauris. Vivamus eu turpis nec nisl ultricies bibendum. Phasellus ut ipsum efficitur, fermentum turpis et, blandit felis.",
    upload_date: "02 July 2021",
    tags: ["Popular", "Trending", "News"],
  },
  {
    title: "The Growing Appeal of Real Estate in Dubai",
    blog: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sit amet tincidunt elit. Nam porttitor sem et neque luctus, in sodales ligula bibendum. Ut non ipsum convallis, faucibus felis ac, laoreet nunc. Integer fermentum lacinia mauris, ac vehicula urna viverra eget. Suspendisse sed semper libero. Phasellus et nisl vestibulum, congue sem et, aliquam arcu. Integer non purus malesuada, bibendum eros sit amet, scelerisque neque.",
    upload_date: "02 July 2021",
    tags: ["Trending", "Recent", "News"],
  },
  {
    title: "Dubai's Real Estate Boom: Opportunities for All",
    blog: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus vehicula turpis nec tempor tristique. Fusce nec velit vel ligula tincidunt tincidunt. Nulla bibendum, libero vitae sodales convallis, magna libero ultrices elit, quis hendrerit ligula ligula in nunc. Vestibulum sit amet mollis erat. Integer id lectus id neque pretium tempor. Vivamus tempor lorem ut lectus scelerisque, non rhoncus est ultricies. Curabitur tincidunt metus non eros varius euismod.",
    upload_date: "02 July 2021",
    tags: ["Discount", "Popular", "Trending"],
  },
  {
    title: "Invest in Dubai's Thriving Waterfront Properties",
    blog: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus, nisi sed tincidunt vulputate, purus nulla pretium arcu, at sodales augue augue et risus. Sed porttitor sodales elit sit amet gravida. Suspendisse vitae purus a arcu malesuada blandit. Donec accumsan, lacus ut fermentum facilisis, risus nulla scelerisque sapien, a fringilla turpis lacus a lacus. Praesent vestibulum tellus ut odio gravida tincidunt.",
    upload_date: "02 July 2021",
    tags: ["News", "Recent", "Trending"],
  },
  {
    title: "Dubai: A City of Endless Investment Possibilities",
    blog: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin id magna consectetur, feugiat justo vel, interdum nisl. Nulla euismod diam eget risus blandit, vitae scelerisque libero ultricies. In hac habitasse platea dictumst. Donec auctor, mauris vel interdum sodales, metus justo vulputate arcu, id dictum est orci at libero. Aliquam erat volutpat. Integer posuere lectus et nunc tempor gravida. Vivamus at accumsan erat.",
    upload_date: "02 July 2021",
    tags: ["Popular", "Trending", "Discount"],
  },
  {
    title: "Why Dubai Remains a Top Choice for Investors",
    blog: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla facilisi. Praesent ut malesuada ligula, quis congue augue. Etiam ac mauris id eros tincidunt ultricies a nec lectus. Ut eget risus sit amet ligula fermentum dapibus. Nullam tristique, ligula in tincidunt dapibus, odio nisl vehicula ex, id luctus lectus quam vitae lorem. Vestibulum volutpat felis nec augue consequat lacinia.",
    upload_date: "02 July 2021",
    tags: ["Trending", "Popular", "News"],
  },
  {
    title: "The Role of Technology in Real Estate Investment",
    blog: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent consectetur libero ut efficitur pretium. Etiam cursus odio a sapien vestibulum, non rutrum arcu condimentum. Sed eget nisi id metus finibus eleifend. Proin interdum, ipsum quis dapibus cursus, lectus turpis vehicula enim, nec consequat nisi eros sit amet erat. Sed ultricies risus vel libero gravida, quis volutpat neque pretium.",
    upload_date: "02 July 2021",
    tags: ["Trending", "Recent", "News"],
  },
  {
    title: "Affordable Real Estate in Dubai: Fact or Myth?",
    blog: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non erat non turpis fermentum tempus. Curabitur eget dolor ut arcu aliquam pharetra. Donec malesuada magna sit amet libero eleifend feugiat. Praesent ut justo quis nisi aliquet posuere. Sed ut sem vel nulla sodales tempor ut a dolor. Suspendisse viverra erat et justo bibendum, sed vulputate ipsum elementum.",
    upload_date: "02 July 2021",
    tags: ["Recent", "Popular", "News"],
  },
  {
    title: "Middle East's Promising Real Estate Investments",
    blog: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi varius, justo et sagittis mollis, metus ante molestie quam, vel venenatis magna orci eget purus. In egestas ligula et ligula ornare, eget vehicula odio tincidunt. Cras tristique libero a eros ultricies, quis pulvinar sapien sollicitudin. Aenean non nisl in justo sollicitudin vehicula nec sed nisl. Integer fermentum nec nisi sit amet tempus.",
    upload_date: "02 July 2021",
    tags: ["Discount", "Trending", "Popular"],
  },
  {
    title: "Dubai's Real Estate Market: A Global Perspective",
    blog: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse vehicula justo eu urna fringilla suscipit. Pellentesque molestie sapien nec vehicula iaculis. Donec id orci id magna tincidunt facilisis. Quisque et turpis et elit venenatis sagittis. Aliquam rhoncus, mauris sed fermentum iaculis, felis odio malesuada nisi, sit amet aliquet sapien lacus vitae est. Nam cursus erat at dolor sollicitudin cursus.",
    upload_date: "02 July 2021",
    tags: ["Trending", "News", "Discount"],
  },

  {
    title: "Exploring Emerging Real Estate Markets Worldwide",
    blog: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean condimentum, nunc et malesuada facilisis, arcu eros pharetra lorem, vitae hendrerit sapien libero non lectus. Sed vulputate mi vel nisi facilisis, sed hendrerit tortor dictum. Ut bibendum nulla nec sapien eleifend, vitae volutpat sapien sollicitudin. Praesent accumsan risus et sapien consectetur, in feugiat ligula lacinia. Integer in dapibus libero, sed tincidunt elit.",
    upload_date: "02 July 2021",
    tags: ["Trending", "News", "Popular"],
  },
  {
    title: "Investing in Global Waterfront Properties",
    blog: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vestibulum magna ac lacus scelerisque, ut malesuada sapien consequat. Donec convallis sapien non orci pellentesque fermentum. Suspendisse varius augue a sapien vestibulum, vel fermentum ipsum venenatis. Nam bibendum, magna at ultrices bibendum, dolor nulla pharetra odio, vel vehicula turpis magna at velit. Curabitur efficitur nisl sit amet turpis dictum, in rhoncus neque hendrerit.",
    upload_date: "02 July 2021",
    tags: ["Trending", "Recent", "News"],
  },
  {
    title: "Why Europe Attracts Global Real Estate Investors",
    blog: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam suscipit magna nec lectus convallis interdum. Proin sit amet nisi venenatis, vulputate ex at, dictum mi. Fusce consectetur urna in eros lacinia, vel bibendum mi pellentesque. Vestibulum a interdum mauris. Integer bibendum congue purus, at gravida eros vehicula vel. Duis tristique sapien et magna bibendum, nec accumsan sapien hendrerit.",
    upload_date: "02 July 2021",
    tags: ["Popular", "News", "Recent"],
  },
  {
    title: "Asia’s Rapidly Growing Real Estate Opportunities",
    blog: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur vehicula ex ut metus posuere, non vehicula nisi gravida. Vivamus non malesuada erat, quis consequat libero. Phasellus ac enim in libero suscipit egestas. Quisque volutpat sem quis purus efficitur, sed efficitur lectus posuere. Mauris id sapien ac neque vehicula iaculis nec ut mauris. Nulla convallis urna at metus varius, in laoreet neque efficitur.",
    upload_date: "02 July 2021",
    tags: ["Recent", "Trending", "Discount"],
  },
  {
    title: "Top 5 Real Estate Investment Destinations Globally",
    blog: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam erat volutpat. Proin volutpat tellus sed lacus hendrerit, sit amet lacinia purus sodales. Morbi in orci purus. Sed efficitur ex vel erat tincidunt, a faucibus est ultricies. Pellentesque eu sapien ornare, dapibus eros nec, dictum mauris. Vivamus eu turpis nec nisl ultricies bibendum. Phasellus ut ipsum efficitur, fermentum turpis et, blandit felis.",
    upload_date: "02 July 2021",
    tags: ["Popular", "Trending", "News"],
  },
  {
    title: "Real Estate Investments in Coastal Regions",
    blog: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean aliquam orci nec metus ultricies, vitae ullamcorper orci elementum. Quisque vehicula, neque sed venenatis vehicula, magna ligula accumsan velit, in accumsan lorem orci quis ligula. Suspendisse vehicula nulla id risus consectetur vehicula. Duis a arcu nec tortor pretium hendrerit. Aliquam maximus, lorem non faucibus hendrerit, turpis tortor aliquet risus, non accumsan elit nulla et urna.",
    upload_date: "02 July 2021",
    tags: ["Trending", "Discount", "News"],
  },
  {
    title: "Maximizing Returns with Smart Global Real Estate",
    blog: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ac leo eu lorem tincidunt pharetra. Sed id lacinia lacus. Quisque tincidunt nunc vitae purus laoreet, sit amet accumsan nunc pretium. Suspendisse potenti. Integer tempor enim sit amet ante sodales, vitae sodales ligula blandit. Integer id ligula eu purus suscipit vehicula. Phasellus dictum, ipsum ac cursus sagittis, velit odio tincidunt erat, sit amet gravida elit mi nec nunc.",
    upload_date: "02 July 2021",
    tags: ["News", "Trending", "Popular"],
  },
  {
    title: "Invest in Dubai's Thriving Waterfront Properties",
    blog: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus, nisi sed tincidunt vulputate, purus nulla pretium arcu, at sodales augue augue et risus. Sed porttitor sodales elit sit amet gravida. Suspendisse vitae purus a arcu malesuada blandit. Donec accumsan, lacus ut fermentum facilisis, risus nulla scelerisque sapien, a fringilla turpis lacus a lacus. Praesent vestibulum tellus ut odio gravida tincidunt.",
    upload_date: "02 July 2021",
    tags: ["News", "Recent", "Trending"],
  },
  {
    title: "Luxury Residences in Global Hotspots",
    blog: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed a lorem in dolor viverra porttitor. Nam consequat lacus non nulla fermentum, non pellentesque elit gravida. Pellentesque vel magna nec lorem tristique dictum non ut lorem. Suspendisse vel varius nunc. Praesent tincidunt vehicula nunc, eget pellentesque nisi aliquet id. Ut non felis ut ipsum ornare pellentesque ut vel dolor.",
    upload_date: "02 July 2021",
    tags: ["Recent", "Popular", "News"],
  },
];
